### ISSUE TITLE
Start loading the mp3s in the background, so user doesn't have to wait on first clicks

### ISSUE THREAD

**Issue by anicholson** [jennz0r/developers#1]
Hi!

I loved this little gem, very fun :) I felt a little frustrated though when I had to wait for the sound to download every time I clicked. If the app downloaded these in the background as the page loaded, there'd be much less wait time and it would feel much more seamless 👍

DEVELOPERS!

**Comment by jennz0r** [comment]
Thank you! I'll take a look into it. I thought I'd tried loading them in the background, but I guess I haven't.
